apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wtsa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-wtsa@sha256:b8a10f3b8dc0413af03916949c563daa8a49cc0c66eb3c9e62a5ac6aecf1068f
        name: my-nodejs
        resources: {}
status: {}
